[
  .taxon_id,
  .scientific_name,
  ._COMMON_NAME_,
  ._ABBREV_,
  ._GENOME_ACCESSION_,
  ._GENOME_FTP_URL_,
  ._REFSEQ_ANN_REPORT_URL_,
  ._REFSEQ_ANN_NAME_,
  ._ASSEMBLY_PROVIDER_NAME_,
  ._ANNOTATION_PROVIDER_NAME_,
  ._ANNOTATION_SOURCE_,
  ._ANNOTATION_SOURCE_SFX_,
  ._LOAD_GFF3_ANALYSIS_NAME_,
  ._ANNOTATION_GFF3_
] | join("\t")
